/**
 * Create editor-style.css from style.css by removing everything between
 * comments with "start non-editor" to "end non-editor"
 */

/* eslint-disable no-console */
import fs from 'fs';
import path from 'path';

const args = process.argv.slice( 2 );
if ( args.length !== 1 ) {
	console.error( 'Usage: <theme-directory>' );
	process.exit( 1 );
}
const themeDir = args.pop();
try {
	const stats = fs.lstatSync( themeDir, { throwIfNoEntry: false } );
	if ( ! stats?.isDirectory() ) {
		console.error( `Unknown directory ${ themeDir }` );
		process.exit( 1 );
	}
	let styles = fs.readFileSync( path.join( themeDir, 'style.css' ), 'utf8' );
	styles = styles.replaceAll(
		/\/\* *start non-editor.*?end non-editor *\*\//gis,
		''
	);
	// get rid of the theme comment
	styles = styles.replace( /^\/\*.*?\*\/[\n\r\s]*/s, '' );
	styles =
		'/* Do not edit this file! Generated from style.css */\n\n' + styles;
	fs.writeFileSync( path.join( themeDir, 'editor-style.css' ), styles, {
		encoding: 'utf8',
		mode: 0o644,
	} );
} catch ( err ) {
	console.error( err );
}
