/**
 * Create editor-style.css from style.css by removing everything between
 * comments with "start non-editor" to "end non-editor"
 */

import fs from 'fs';
import path from 'path';

if ( ! process.env.npm_config_www ) {
	process.stderr.write( 'No www environment variable set in .npmrc' );
	process.exit( 1 );
}
const themeDir = path.join(
	process.env.npm_config_www,
	'/wp-content/themes/lax'
);
try {
	const stats = fs.lstatSync( themeDir, { throwIfNoEntry: false } );
	if ( ! stats?.isDirectory() ) {
		process.stderr.write( `Unknown directory ${ themeDir }` );
		process.exit( 1 );
	}
	let styles = fs.readFileSync( path.join( themeDir, 'style.css' ), 'utf8' );
	styles = styles.replaceAll(
		/\/\* *start non-editor.*?end non-editor *\*\//gis,
		''
	);
	// get rid of the theme comment
	styles = styles.replace( /^\/\*.*?\*\/[\n\r\s]*/s, '' );
	styles =
		'/* Do not edit this file! Generated from style.css */\n\n' + styles;
	const out = path.join( themeDir, 'editor-style.css' );
	fs.writeFileSync( out, styles, {
		encoding: 'utf8',
		mode: 0o644,
	} );
	process.stdout.write( `Written to ${ out }\n` );
} catch ( err ) {
	process.stderr.write( `Error: ${ err }\n` );
	process.exit( 1 );
}
