/**
 * Create editor-style.css from style.css by removing everything between
 * comments with "start non-editor" to "end non-editor"
 */

import fs from 'fs';
import path from 'path';

if ( ! process.env.SEMLA_WWW ) {
	throw new Error( 'Environment variable SEMLA_WWW not set' );
}
const themeDir = path.join( process.env.SEMLA_WWW, '/wp-content/themes/lax' );
const stats = fs.lstatSync( themeDir, { throwIfNoEntry: false } );
if ( ! stats?.isDirectory() ) {
	throw new Error( `Unknown directory ${ themeDir }` );
}
let styles = fs.readFileSync( path.join( themeDir, 'style.css' ), 'utf8' );
styles = styles.replaceAll(
	/\s*\/\* *start non-editor.*?end non-editor *\*\//gis,
	''
);
// get rid of the theme comment
styles = styles.replace( /^\/\*.*?\*\/[\n\r\s]*/s, '' );
styles = '/* Do not edit this file! Generated from style.css */\n\n' + styles;
const out = path.join( themeDir, 'editor-style.css' );
fs.writeFileSync( out, styles, {
	encoding: 'utf8',
	mode: 0o644,
} );
process.stdout.write( `Written to ${ out }\n` );
